version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./docker/php
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ./code:/code
      - ./docker/php/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini
